TRANSLATIONS = {
    "en": {
        "title":              "WindGuard",
        "caption":            "Real-time wind-based emission alert system — Monastir & Mahdia",
        "wind_speed":         "Wind Speed",
        "wind_direction":     "Wind Direction",
        "factories":          "Factories",
        "protected_zones":    "Protected Zones",
        "people_at_risk":     "People at risk",
        "factories_risk":     "Factories at risk",
        "safe_factories":     "Safe factories",
        "all_clear":          "All clear — no emission risk detected right now.",
        "alert_banner":       "active alert(s) — factories must act now!",
        "live_map":           "Live Risk Map",
        "warning_alerts":     "Warning Alerts",
        "safe_panel":         "Safe Factories",
        "forecast_chart":     "Wind Speed Forecast (next 24h)",
        "last_updated":       "Last updated",
        "tab_live":           "📡 Live Monitor",
        "tab_whatif":         "🧪 What-if Simulator",
        "tab_history":        "📜 Alert History",
        "tab_analysis":       "🔬 Analysis",
        "tab_tanks":          "🛢️ Smoke Tanks",
        "no_warnings":        "No warnings right now.",
        "smoke_travels":      "smoke travels",
        "in":                 "in",
        "wind_at":            "Wind at",
        "from":               "from",
        "hours_ahead":        "Hours ahead",
        "simulation_map":     "Simulation Map",
        "scenario_summary":   "Scenario Summary",
        "results":            "Results",
        "no_risk":            "No factories at risk.",
        "alert_history":      "Alert History Log",
        "history_caption":    "Every alert ever triggered is saved here automatically",
        "total_alerts":       "Total alerts",
        "factories_triggered":"Factories triggered",
        "avg_risk":           "Avg risk score",
        "highest_risk":       "Highest risk ever",
        "most_affected":      "Most affected zone",
        "most_alerted":       "Most alerted factory",
        "factory_ranking":    "Factory Risk Ranking",
        "full_log":           "Full Alert Log",
        "filter_factory":     "Filter by factory",
        "filter_zone":        "Filter by zone type",
        "download_csv":       "Download history as CSV",
        "advanced_analysis":  "Advanced Analysis",
        "anomaly_title":      "Wind Anomaly Detection",
        "no_anomaly":         "No anomalies detected — wind conditions are stable.",
        "nl_alerts":          "Natural Language Alerts",
        "all_safe":           "All factories are currently safe.",
        "forecast_12h":       "12-Hour Risk Forecast",
        "risk_per_hour":      "Risk Score per Hour",
        "hourly_table":       "Hourly Forecast Table",
        "factory_profiles":   "Factory Profiles",
        "select_factory":     "Select a factory to view its profile",
        "sector":             "Sector",
        "employees":          "Employees",
        "daily_emissions":    "Daily emissions",
        "main_pollutants":    "Main pollutants",
        "operating_hours":    "Operating hours",
        "certification":      "Certification",
        "contact":            "Contact",
        "risk_level":         "Risk level",
        "tank_monitor":       "Smoke Tank Monitor",
        "tank_caption":       "Real-time tank fill levels",
        "critical_tanks":     "Critical tanks",
        "warning_tanks":      "Warning tanks",
        "normal_tanks":       "Normal tanks",
        "reduction_calc":     "Emission Reduction Calculator",
        "reduction_caption":  "How much does each factory need to cut?",
        "no_reduction":       "No reductions needed — all factories operating normally.",
        "reduce_by":          "Reduce emissions by",
        "within":             "within",
        "to_prevent":         "to prevent smoke reaching",
        "current_risk":       "Current risk",
        "distance":           "Distance",
        "forecast_horizon":   "Forecast horizon (hours)",
        "wind_speed_label":   "Wind speed (km/h)",
        "direction_label":    "Wind direction (degrees)",
        "factories_checked":  "Factories checked",
        "zones_at_risk":      "Zones at risk",
        "travel_distance":    "Travel distance",
        "sidebar_title":      "WindGuard System",
        "sidebar_caption":    "Emission Alert System",
        "monitored":          "Factories monitored",
        "lang_label":         "Language",
        "alert_details":      "Alert Details",
        "peak_danger":        "Peak danger at",
        "max_risk":           "Max risk",
        "no_peak":            "No significant risk in the next 12 hours.",
        "anomalies_found":    "anomaly(ies) detected!",
        "risk_score_time":    "Risk Score Over Time",
    },
    "fr": {
        "title":              "WindGuard",
        "caption":            "Système d'alerte d'émission en temps réel — Monastir & Mahdia",
        "wind_speed":         "Vitesse du vent",
        "wind_direction":     "Direction du vent",
        "factories":          "Usines",
        "protected_zones":    "Zones protégées",
        "people_at_risk":     "Personnes à risque",
        "factories_risk":     "Usines à risque",
        "safe_factories":     "Usines sûres",
        "all_clear":          "Tout va bien — aucun risque d'émission détecté.",
        "alert_banner":       "alerte(s) active(s) — les usines doivent agir maintenant!",
        "live_map":           "Carte des risques en direct",
        "warning_alerts":     "Alertes d'avertissement",
        "safe_panel":         "Usines sûres",
        "forecast_chart":     "Prévision vitesse du vent (24h)",
        "last_updated":       "Dernière mise à jour",
        "tab_live":           "📡 Surveillance",
        "tab_whatif":         "🧪 Simulateur",
        "tab_history":        "📜 Historique",
        "tab_analysis":       "🔬 Analyse",
        "tab_tanks":          "🛢️ Réservoirs",
        "no_warnings":        "Aucun avertissement pour le moment.",
        "smoke_travels":      "la fumée parcourt",
        "in":                 "en",
        "wind_at":            "Vent à",
        "from":               "depuis",
        "hours_ahead":        "Heures à l'avance",
        "simulation_map":     "Carte de simulation",
        "scenario_summary":   "Résumé du scénario",
        "results":            "Résultats",
        "no_risk":            "Aucune usine à risque.",
        "alert_history":      "Historique des alertes",
        "history_caption":    "Chaque alerte déclenchée est sauvegardée ici automatiquement",
        "total_alerts":       "Total des alertes",
        "factories_triggered":"Usines déclenchées",
        "avg_risk":           "Score de risque moyen",
        "highest_risk":       "Risque le plus élevé",
        "most_affected":      "Zone la plus touchée",
        "most_alerted":       "Usine la plus alertée",
        "factory_ranking":    "Classement des usines",
        "full_log":           "Journal complet des alertes",
        "filter_factory":     "Filtrer par usine",
        "filter_zone":        "Filtrer par type de zone",
        "download_csv":       "Télécharger l'historique en CSV",
        "advanced_analysis":  "Analyse avancée",
        "anomaly_title":      "Détection d'anomalies de vent",
        "no_anomaly":         "Aucune anomalie détectée — conditions stables.",
        "nl_alerts":          "Alertes en langage naturel",
        "all_safe":           "Toutes les usines sont actuellement sûres.",
        "forecast_12h":       "Prévision des risques sur 12 heures",
        "risk_per_hour":      "Score de risque par heure",
        "hourly_table":       "Tableau des prévisions horaires",
        "factory_profiles":   "Profils des usines",
        "select_factory":     "Sélectionner une usine",
        "sector":             "Secteur",
        "employees":          "Employés",
        "daily_emissions":    "Émissions journalières",
        "main_pollutants":    "Polluants principaux",
        "operating_hours":    "Heures d'exploitation",
        "certification":      "Certification",
        "contact":            "Contact",
        "risk_level":         "Niveau de risque",
        "tank_monitor":       "Moniteur de réservoirs",
        "tank_caption":       "Niveaux de remplissage en temps réel",
        "critical_tanks":     "Réservoirs critiques",
        "warning_tanks":      "Réservoirs en alerte",
        "normal_tanks":       "Réservoirs normaux",
        "reduction_calc":     "Calculateur de réduction des émissions",
        "reduction_caption":  "De combien chaque usine doit-elle réduire?",
        "no_reduction":       "Aucune réduction nécessaire — opérations normales.",
        "reduce_by":          "Réduire les émissions de",
        "within":             "dans",
        "to_prevent":         "pour éviter que la fumée atteigne",
        "current_risk":       "Risque actuel",
        "distance":           "Distance",
        "forecast_horizon":   "Horizon de prévision (heures)",
        "wind_speed_label":   "Vitesse du vent (km/h)",
        "direction_label":    "Direction du vent (degrés)",
        "factories_checked":  "Usines vérifiées",
        "zones_at_risk":      "Zones à risque",
        "travel_distance":    "Distance parcourue",
        "sidebar_title":      "Système WindGuard",
        "sidebar_caption":    "Système d'alerte d'émission",
        "monitored":          "Usines surveillées",
        "lang_label":         "Langue",
        "alert_details":      "Détails des alertes",
        "peak_danger":        "Danger maximal à",
        "max_risk":           "Risque max",
        "no_peak":            "Aucun risque significatif dans les 12 prochaines heures.",
        "anomalies_found":    "anomalie(s) détectée(s)!",
        "risk_score_time":    "Score de risque dans le temps",
    },
    "ar": {
        "title":              "WindGuard",
        "caption":            "نظام تنبيه الانبعاثات في الوقت الفعلي — المنستير والمهدية",
        "wind_speed":         "سرعة الرياح",
        "wind_direction":     "اتجاه الرياح",
        "factories":          "المصانع",
        "protected_zones":    "المناطق المحمية",
        "people_at_risk":     "الأشخاص في خطر",
        "factories_risk":     "المصانع في خطر",
        "safe_factories":     "المصانع الآمنة",
        "all_clear":          "كل شيء على ما يرام — لا يوجد خطر انبعاثات.",
        "alert_banner":       "تنبيه/تنبيهات نشطة — يجب على المصانع التصرف الآن!",
        "live_map":           "خريطة المخاطر المباشرة",
        "warning_alerts":     "تحذيرات",
        "safe_panel":         "المصانع الآمنة",
        "forecast_chart":     "توقعات سرعة الرياح (24 ساعة)",
        "last_updated":       "آخر تحديث",
        "tab_live":           "📡 المراقبة",
        "tab_whatif":         "🧪 المحاكاة",
        "tab_history":        "📜 السجل",
        "tab_analysis":       "🔬 التحليل",
        "tab_tanks":          "🛢️ الخزانات",
        "no_warnings":        "لا تحذيرات الآن.",
        "smoke_travels":      "يقطع الدخان",
        "in":                 "في",
        "wind_at":            "الرياح بسرعة",
        "from":               "من",
        "hours_ahead":        "ساعات للأمام",
        "simulation_map":     "خريطة المحاكاة",
        "scenario_summary":   "ملخص السيناريو",
        "results":            "النتائج",
        "no_risk":            "لا توجد مصانع في خطر.",
        "alert_history":      "سجل التنبيهات",
        "history_caption":    "كل تنبيه يتم تشغيله يتم حفظه هنا تلقائياً",
        "total_alerts":       "إجمالي التنبيهات",
        "factories_triggered":"المصانع التي تم تنبيهها",
        "avg_risk":           "متوسط درجة الخطر",
        "highest_risk":       "أعلى خطر",
        "most_affected":      "المنطقة الأكثر تضرراً",
        "most_alerted":       "المصنع الأكثر تنبيهاً",
        "factory_ranking":    "تصنيف المصانع",
        "full_log":           "سجل التنبيهات الكامل",
        "filter_factory":     "تصفية حسب المصنع",
        "filter_zone":        "تصفية حسب نوع المنطقة",
        "download_csv":       "تحميل السجل كـ CSV",
        "advanced_analysis":  "التحليل المتقدم",
        "anomaly_title":      "كشف شذوذات الرياح",
        "no_anomaly":         "لا شذوذات — الرياح مستقرة.",
        "nl_alerts":          "التنبيهات بلغة طبيعية",
        "all_safe":           "جميع المصانع آمنة حالياً.",
        "forecast_12h":       "توقعات الخطر لـ 12 ساعة",
        "risk_per_hour":      "درجة الخطر في الساعة",
        "hourly_table":       "جدول التوقعات بالساعة",
        "factory_profiles":   "ملفات المصانع",
        "select_factory":     "اختر مصنعاً لعرض ملفه",
        "sector":             "القطاع",
        "employees":          "الموظفون",
        "daily_emissions":    "الانبعاثات اليومية",
        "main_pollutants":    "الملوثات الرئيسية",
        "operating_hours":    "ساعات العمل",
        "certification":      "الشهادة",
        "contact":            "التواصل",
        "risk_level":         "مستوى الخطر",
        "tank_monitor":       "مراقبة الخزانات",
        "tank_caption":       "مستويات امتلاء الخزانات",
        "critical_tanks":     "خزانات حرجة",
        "warning_tanks":      "خزانات تحذير",
        "normal_tanks":       "خزانات عادية",
        "reduction_calc":     "حاسبة تخفيض الانبعاثات",
        "reduction_caption":  "كم يجب على كل مصنع تخفيضه؟",
        "no_reduction":       "لا تخفيضات مطلوبة — عمليات طبيعية.",
        "reduce_by":          "تخفيض الانبعاثات بنسبة",
        "within":             "خلال",
        "to_prevent":         "لمنع وصول الدخان إلى",
        "current_risk":       "الخطر الحالي",
        "distance":           "المسافة",
        "forecast_horizon":   "أفق التنبؤ (ساعات)",
        "wind_speed_label":   "سرعة الرياح (كم/ساعة)",
        "direction_label":    "اتجاه الرياح (درجات)",
        "factories_checked":  "المصانع المفحوصة",
        "zones_at_risk":      "المناطق في خطر",
        "travel_distance":    "المسافة المقطوعة",
        "sidebar_title":      "نظام WindGuard",
        "sidebar_caption":    "نظام تنبيه الانبعاثات",
        "monitored":          "المصانع المراقبة",
        "lang_label":         "اللغة",
        "alert_details":      "تفاصيل التنبيهات",
        "peak_danger":        "أقصى خطر في",
        "max_risk":           "أقصى خطر",
        "no_peak":            "لا خطر كبير في الـ 12 ساعة القادمة.",
        "anomalies_found":    "شذوذ/شذوذات مكتشفة!",
        "risk_score_time":    "درجة الخطر عبر الزمن",
    }
}

def t(key, lang="en"):
    return TRANSLATIONS.get(lang, TRANSLATIONS["en"]).get(key, key)